package it.polimi.ingsw.gc19.Networking.Server.Message.GameHandling.Errors;

public enum Error{
    CLIENT_NOT_REGISTERED_TO_SERVER,
    PLAYER_NAME_ALREADY_IN_USE,
    GAME_NAME_ALREADY_IN_USE,
    PLAYER_NOT_IN_GAME,
    GAME_NOT_FOUND,
    GAME_NOT_ACCESSIBLE,
    CLIENT_ALREADY_CONNECTED_TO_SERVER,
    PLAYER_ALREADY_REGISTERED_TO_SOME_GAME
}
