package it.polimi.ingsw.gc19.Networking.Server.Message.Action.RefusedAction;

public enum ErrorType{
    INVALID_ANCHOR_ERROR,
    INVALID_CARD_ERROR,
    EMPTY_DECK,
    EMPTY_TABLE_SLOT,
    INVALID_INITIAL_CARD_ERROR,
    INVALID_GOAL_CARD_ERROR,
    INVALID_TURN,
    INVALID_GAME_STATE,
    INVALID_TURN_STATE,
    NAME_ALREADY_IN_USE,
    COLOR_ALREADY_CHOSEN,
    GENERIC;
}
