package it.polimi.ingsw.gc19.View.Listeners;

public enum ListenerType {
    TURN_LISTENER, SETUP_LISTENER, CHAT_LISTENER, GAME_EVENTS_LISTENER, GAME_HANDLING_EVENTS_LISTENER, DISCONNECTION_LISTENER, PLAYER_CREATION_LISTENER;
}
