package it.polimi.ingsw.gc19.View.Listeners;

public enum ListenerType {
    TURN_LISTENER,
    SETUP_LISTENER,
    CHAT_LISTENER,
    GAME_HANDLING_EVENTS_LISTENER,
    PLAYER_CREATION_LISTENER,
    STATE_LISTENER,
    LOCAL_MODEL_LISTENER,
    STATION_LISTENER,
    TABLE_LISTENER;
}
