name: Build and Package

on:
  push:
    branches:
      - main
      - fvilla
  pull_request:
    branches:
      - main
      - fvilla

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build ClientApp and ServerApp JAR
        run: mvn clean compile install -D"maven.test.skip"="true"

      - name: Archive the JAR files
        uses: actions/upload-artifact@v4
        with:
          name: client-and-server-jars
          path: |
            target/GC19-client.jar
            target/GC19-server.jar
